# Generated by Django 4.2.3 on 2023-07-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestSeguir', '0009_alter_egresado_carrera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enc_egre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr1', models.CharField(max_length=1000)),
                ('pr2', models.CharField(max_length=1000)),
                ('pr3', models.CharField(max_length=1000)),
                ('pr4', models.CharField(max_length=1000)),
                ('pr5', models.CharField(max_length=1000)),
                ('pr6', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Enc_emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr1', models.CharField(max_length=1000)),
                ('pr2', models.CharField(max_length=1000)),
                ('pr3', models.CharField(max_length=1000)),
                ('pr4', models.CharField(max_length=1000)),
                ('pr5', models.CharField(max_length=1000)),
                ('pr6', models.CharField(max_length=1000)),
            ],
        ),
    ]
