# Generated by Django 4.2.3 on 2023-07-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestSeguir', '0010_enc_egre_enc_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enc_egre',
            name='pr1',
            field=models.TextField(max_length=999),
        ),
        migrations.AlterField(
            model_name='enc_egre',
            name='pr2',
            field=models.TextField(max_length=999),
        ),
        migrations.AlterField(
            model_name='enc_egre',
            name='pr3',
            field=models.TextField(max_length=999),
        ),
        migrations.AlterField(
            model_name='enc_egre',
            name='pr4',
            field=models.TextField(max_length=999),
        ),
        migrations.AlterField(
            model_name='enc_egre',
            name='pr5',
            field=models.TextField(max_length=999),
        ),
        migrations.AlterField(
            model_name='enc_egre',
            name='pr6',
            field=models.TextField(max_length=999),
        ),
        migrations.AlterField(
            model_name='enc_emp',
            name='pr1',
            field=models.TextField(max_length=999),
        ),
        migrations.AlterField(
            model_name='enc_emp',
            name='pr2',
            field=models.TextField(max_length=999),
        ),
        migrations.AlterField(
            model_name='enc_emp',
            name='pr3',
            field=models.TextField(max_length=999),
        ),
        migrations.AlterField(
            model_name='enc_emp',
            name='pr4',
            field=models.TextField(max_length=999),
        ),
        migrations.AlterField(
            model_name='enc_emp',
            name='pr5',
            field=models.TextField(max_length=999),
        ),
        migrations.AlterField(
            model_name='enc_emp',
            name='pr6',
            field=models.TextField(max_length=1000),
        ),
    ]
